__author__ = "Roberto Medina"
__copyright__ = "Copyright 2021, Roberto Carlos Medina"
__version__ = "0.0.1"
__maintainer__ = "Roberto Medina"
__email__ = "robertocarlosmedina.dev@gmail.com "
__status__ = "Production"

"""
    This is the class where all the game loop is controlled, and where all the action are
    controlled. And also all the cubes generated by the Cube class are controlled by here.
"""

from typing import Literal
import pygame
from time import sleep
from src.support.font import Game_fonts as fonts
from src.support.colors import Game_color as color
from src.support.auxiliar_functions import write_from_file

class Game_loop:
    
    game_events: pygame.event        # Hold the current games events
    mouse_position: tuple            # To store and refresh the mouse position
    
    def __init__(self, screen: pygame.Surface, screen_size: list, game_mode = None ) -> None:
        self.screen = screen
        self.screen_size = screen_size

    def game_over(self) -> Literal["game_over"]:
        write_from_file("./data/end_game_values.txt", "w","string example data to bee displayed in game over")
        
        return "game_over"

    def run_link(self, game_events :pygame.event) -> str:
        self.game_events = game_events
        self.mouse_position = pygame.mouse.get_pos()

            # return self.game_over(self.ttt.verificaGanhador())
        
        return "game_loop"
